# Generated by Django 5.1.2 on 2026-01-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('introduction', models.TextField(max_length=500, verbose_name='Introduction')),
                ('summary', models.TextField(max_length=500, verbose_name='Summary')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
