# Generated by Django 5.1.2 on 2026-01-31 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FederationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploadedfiles', verbose_name='File')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='ratinglists', verbose_name='File')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('original_file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True, unique=True)),
                ('player_total', models.IntegerField(blank=True, null=True)),
                ('has_player_profiles', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('player_total', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FederationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('federation_code', models.CharField(blank=True, max_length=5, null=True)),
                ('player_total', models.CharField(blank=True, max_length=100, null=True)),
                ('rating_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('federation_code'), models.F('rating_date'), name='unique_federation_code_and_rating_date')],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('rating_date', models.DateTimeField()),
                ('index', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('fideid', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.CharField(blank=True, max_length=100, null=True)),
                ('kfactor', models.IntegerField(blank=True, null=True)),
                ('games', models.IntegerField(blank=True, null=True)),
                ('birthday', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('w_title', models.CharField(blank=True, max_length=100, null=True)),
                ('o_title', models.CharField(blank=True, max_length=100, null=True)),
                ('foa_title', models.CharField(blank=True, max_length=100, null=True)),
                ('flag', models.CharField(blank=True, max_length=100, null=True)),
                ('rating_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratinglists.ratinglist')),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('fideid'), models.F('rating_date'), name='unique_fideid_and_rating_date')],
            },
        ),
    ]
