# Generated by Django 5.1.2 on 2026-02-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratinglists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federationprofile',
            name='rating_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='rating_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ratinglist',
            name='release_date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
