# Generated by Django 5.1.2 on 2026-02-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratinglists', '0002_alter_federationprofile_rating_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratinglist',
            name='slug',
            field=models.SlugField(default='new', unique=True),
        ),
    ]
