# Generated by Django 5.1.2 on 2026-02-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratinglists', '0003_ratinglist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinglist',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
