# Generated by Django 5.1.2 on 2026-02-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratinglists', '0005_alter_ratinglist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinglist',
            name='slug',
            field=models.SlugField(default=0.5291677047575424, unique=True),
        ),
    ]
