# Generated by Django 5.1.2 on 2026-02-04 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratinglists', '0007_playerprofile_slug_alter_ratinglist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='slug',
        ),
    ]
