# Generated by Django 5.1.2 on 2026-02-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratinglists', '0008_remove_playerprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
