# Generated by Django 5.2.11 on 2026-02-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratinglists', '0009_playerprofile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='posts', verbose_name='File')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('unzipped_file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.DateField(blank=True, null=True, unique=True)),
                ('player_total', models.IntegerField(blank=True, null=True)),
                ('is_extracted', models.BooleanField(default=False)),
            ],
        ),
    ]
